---
- block:
  - name: Set list of path to look for local Grafana configuration directory
    set_fact:
      grafana_search_config_paths: "{{ grafana_search_config_paths }} + [ '{{ grafana_search_config_path }}' ]"
    with_items: "{{ group_names }}"

  - name: Check if Grafana configuration directory exists
    stat:
      path: "{{ item }}"
    register: grafana_config_check
    become: false
    delegate_to: 127.0.0.1
    with_first_found:
      - files: "{{ grafana_search_config_paths }}"
        skip: true

  - name: Set Grafana configuration directory
    set_fact:
      grafana_host_config_path: "{{ grafana_config_check.results[0].stat.path }}"
    when:
      - grafana_config_check.results[0] is defined
      - grafana_config_check.results[0].stat is defined
      - grafana_config_check.results[0].stat.isdir is defined
      - grafana_config_check.results[0].stat.isdir

  - name: Check if Grafana dashboard json files exists
    stat:
      path: "{{ grafana_dashboard_json_path }}"
    become: false
    delegate_to: 127.0.0.1
    register: grafana_dashboard_check
  tags:
    - grafana-dashboard

- name: Check if Grafana plugins files exists
  stat:
    path: "{{ grafana_plugin_path }}"
  become: false
  delegate_to: 127.0.0.1
  register: grafana_plugin_check  