---
- name: Add grafana repository key
  apt_key:
    url: "{{ grafana_apt_key_url }}"
    id: "{{ grafana_apt_key_id }}"

- name: Add grafana apt-repository
  apt_repository:
    repo: "{{ grafana_apt_repo }}"