---
- name: Include OS family specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_os_family }}.yml"
    - default.yml

- include_tasks: grafana_search_config.yml
  tags:
    - grafana-dashboard

- include_tasks: grafana_pre.yml
- include_tasks: grafana_install.yml
  tags:
    - grafana-config

- include_tasks: grafana_provisioning.yml
  when: grafana_enable_provisioning
  tags:
    - grafana-datasource
    - grafana-dashboard

# - include_tasks: grafana_database.yml
#   tags:
#     - grafana-config
#     - grafana-database