---
- name: Include OS family specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_os_family }}.yml"
    - default.yml

- include_tasks: grafana_pre.yml
- include_tasks: grafana_install.yml

- include_tasks: grafana_post.yml
  tags:
    - grafana-config
    - grafana-drop-config

# - include_tasks: grafana_database.yml
#   tags:
#     - grafana-config
#     - grafana-database